package com.seeni.systemmonitor.service;

import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;
import java.util.List;

import com.seeni.systemmonitor.repository.AlertSubscriberRepository;
import com.seeni.systemmonitor.entity.AlertSubscriber;

@Service
public class EmailAlertService {

    private final JavaMailSender mailSender;
    private final AlertSubscriberRepository subscriberRepo;

    public EmailAlertService(JavaMailSender mailSender,
                             AlertSubscriberRepository subscriberRepo) {
        this.mailSender = mailSender;
        this.subscriberRepo = subscriberRepo;
    }

    public void sendIncidentEmail(String summary, String priority) {

        List<AlertSubscriber> subscribers = subscriberRepo.findAll();
        if (subscribers.isEmpty()) {
            System.out.println("No subscribers found. Skipping email alerts.");
            return;
        }

        String subject = "🚨 " + priority + " Server Incident Alert";

        // 📧 Professional Email Body
        String body = """
Dear Team,

An automated incident alert has been generated by the AI System Monitoring Service.

Priority Level: %s

Incident Summary:
%s

Recommended Action:
Please investigate the affected server and take necessary corrective measures.

This is an automated message. No reply is required.

Regards,
AI System Health Monitoring Platform
""".formatted(priority, summary);

        for (AlertSubscriber sub : subscribers) {
            try {
                SimpleMailMessage message = new SimpleMailMessage();
                message.setTo(sub.getEmail());
                message.setSubject(subject);
                message.setText(body);
                mailSender.send(message);

            } catch (Exception e) {
                System.out.println("Failed to send email to " + sub.getEmail() +
                        " : " + e.getMessage());
            }
        }

        System.out.println("📧 Incident email alerts sent successfully!");
    }
}
